#define ED_TEDI_SAMPLE_BOX          1
#define ED_TEDI_SAMPLE              2
#define ED_TEDI_TYPE                5
#define ED_TEDI_TYPE_POPUP          7
#define ED_TEDI_TEXTCOLOR_BOX      15
#define ED_TEDI_TEXTCOLOR          17
#define ED_TEDI_TEXTCOLOR_POPUP    18
#define ED_TEDI_HORPOS             21
#define ED_TEDI_HORPOS_POPUP       23
#define ED_TEDI_SIZE               26
#define ED_TEDI_SIZE_POPUP         28
#define ED_TEDI_TEXT               37
#define ED_TEDI_TMPLT              38
#define ED_TEDI_VALID              39
#define ED_TEDI_FRAMECOLOR_BOX     45
#define ED_TEDI_FRAMECOLOR         47
#define ED_TEDI_FRAMECOLOR_POPUP   48
#define ED_TEDI_PATTERN            67
#define ED_TEDI_INTERCOLOR_BOX     71
#define ED_TEDI_INTERCOLOR         73
#define ED_TEDI_INTERCOLOR_POPUP   74
