#define ED_AFLAGS_EXIT         2
#define ED_AFLAGS_SELECTABLE   5
#define ED_AFLAGS_DRAGABLE     8
#define ED_AFLAGS_TOUCHEXIT   11
#define ED_AFLAGS_EDITABLE    14
#define ED_AFLAGS_ACCEPT      17
#define ED_AFLAGS_DEFAULT     20
#define ED_AFLAGS_RBUTTON     23
#define ED_AFLAGS_SILENT      26
#define ED_AFLAGS_DEFABLE     29
#define ED_AFLAGS_CONST       32
#define ED_AFLAGS_SELECTED    36
#define ED_AFLAGS_CROSSED     39
#define ED_AFLAGS_DISABLED    42
#define ED_AFLAGS_CHECKED     45
#define ED_AFLAGS_OUTLINED    48
#define ED_AFLAGS_SHADOWED    51
#define ED_AFLAGS_3DBOX       54
#define ED_AFLAGS_FL3DNONE    55
#define ED_AFLAGS_FL3DIND     57
#define ED_AFLAGS_FL3DACT     59
#define ED_AFLAGS_FL3DBAK     61
#define ED_AFLAGS_CLLEFT      64
#define ED_AFLAGS_CLRIGHT     67
#define ED_AFLAGS_CLTOP       70
#define ED_AFLAGS_CLBOTTOM    73
