#define ED_BOXED_SAMPLE_BOX      1
#define ED_BOXED_SAMPLE          2
#define ED_BOXED_LENGTH         22
#define ED_BOXED_TEXT            8
#define ED_BOXED_BUBBLE         53
#define ED_BOXED_CONTEXT        54
#define ED_BOXED_TEXTCOL_BOX    12
#define ED_BOXED_TEXTCOL        14
#define ED_BOXED_TEXTCOL_POPUP  15
#define ED_BOXED_DOWNCOL_BOX    44
#define ED_BOXED_DOWNCOL        46
#define ED_BOXED_DOWNCOL_POPUP  47
#define ED_BOXED_UPCOL_BOX      37
#define ED_BOXED_UPCOL          39
#define ED_BOXED_UPCOL_POPUP    40
#define ED_BOXED_MASK_POPUP_BOX 28
#define ED_BOXED_MASK_POPUP     30
#define ED_BOXED_FONTSIZE_BOX   18
#define ED_BOXED_FONTSIZE       20
#define ED_BOXED_THREEDIM       48
#define ED_BOXED_CAPITAL        24
#define ED_BOXED_SECRET         26
