#define ED_FTEXT_SAMPLE_BOX    2
#define ED_FTEXT_SAMPLE        3
#define ED_FTEXT_TEXT1        10
#define ED_FTEXT_TEXT2        11
#define ED_FTEXT_BOLD         13
#define ED_FTEXT_LIGHT        15
#define ED_FTEXT_ITALIC       17
#define ED_FTEXT_UNDERLINED   19
#define ED_FTEXT_OUTLINED     21
#define ED_FTEXT_SHADOWED     23
#define ED_FTEXT_ALIGN_LEFT   26
#define ED_FTEXT_ALIGN_CENTER 28
#define ED_FTEXT_ALIGN_BLOCK  30
#define ED_FTEXT_ALIGN_RIGHT  32
#define ED_FTEXT_FONTNAME     39
#define ED_FTEXT_FONTSIZE     40
#define ED_FTEXT_BUBBLE       43
#define ED_FTEXT_CONTEXT      45
#define ED_FTEXT_FONTSEL_BOX  34
