#define ED_INNER_SAMPLE_BOX        1
#define ED_INNER_SAMPLE            2
#define ED_INNER_INCOL_BOX        36
#define ED_INNER_INCOL            38
#define ED_INNER_INCOL_POPUP      39
#define ED_INNER_INTERCOL_BOX     49
#define ED_INNER_INTERCOL         51
#define ED_INNER_INTERCOL_POPUP   52
#define ED_INNER_OUTCOL_BOX       28
#define ED_INNER_OUTCOL           30
#define ED_INNER_OUTCOL_POPUP     31
#define ED_INNER_TEXTCOL_BOX      10
#define ED_INNER_TEXTCOL          12
#define ED_INNER_TEXTCOL_POPUP    13
#define ED_INNER_STYLE_BOX        43
#define ED_INNER_POS_BOX          17
#define ED_INNER_POS_POPUP        19
#define ED_INNER_SIZE_BOX         22
#define ED_INNER_SIZE_POPUP       24
#define ED_INNER_TEXT             14
#define ED_INNER_BUBBLE           56
#define ED_INNER_CONTEXT          57
#define ED_INNER_DITHER           41
