#define EDIT_MOUSE_FRONT_BOX   11
#define EDIT_MOUSE_FRONT_COLOR 13
#define EDIT_MOUSE_FRONT_POPUP 14
#define EDIT_MOUSE_BACK_BOX    17
#define EDIT_MOUSE_BACK_COLOR  19
#define EDIT_MOUSE_BACK_POPUP  20
#define EDIT_MOUSE_BRUSH       21
#define EDIT_MOUSE_BOX         22
#define EDIT_MOUSE_BOX_X       23
#define EDIT_MOUSE_X           25
#define EDIT_MOUSE_BOX_Y       26
#define EDIT_MOUSE_Y           28
#define EDIT_MOUSE_IMAGE       29
#define EDIT_MOUSE_DRAWFRAME   32
#define EDIT_MOUSE_ICON        33
