#define REF_TYPE_NONE         44
#define REF_TYPE_CLICK        48
#define REF_TYPE_DRAG         50
#define REF_TYPE_DRAW         82
#define REF_TYPE_UO_SERVICE   84
#define REF_TYPE_OPEN         88
#define REF_TYPE_CREATE       90
#define REF_TYPE_INIT         94
#define REF_TYPE_KEYS         96
#define REF_TYPE_CHANGE       98
#define REF_TYPE_REDRAW      100
#define REF_TYPE_TOPPED      102
#define REF_TYPE_CLOSED      104
#define REF_TYPE_ARROWED     108
#define REF_TYPE_HSLIDE      110
#define REF_TYPE_VSLIDE      112
#define REF_TYPE_MOVED       114
#define REF_TYPE_SIZE        116
#define REF_TYPE_FULLED      106
#define REF_TYPE_SERVICE      92
#define REF_TYPE_ICONIFY     118
#define REF_TYPE_UNICONIFY   120
#define REF_TYPE_GEMSCRIPT   122
#define REF_TYPE_ACSINIT0     54
#define REF_TYPE_ACSINIT      56
#define REF_TYPE_TERM         58
#define REF_TYPE_ABOUTME      60
#define REF_TYPE_CLOSE        62
#define REF_TYPE_MESSAGE      64
#define REF_TYPE_MPROTO       66
#define REF_TYPE_TIMER        68
#define REF_TYPE_KEY          70
#define REF_TYPE_BUTTON       72
#define REF_TYPE_MOUSE        74
#define REF_TYPE_WIKEY        76
#define REF_TYPE_SYS_GEMSCRIPT 78

#define EDIT_REF_EXTERN       3
#define EDIT_REF_TYPE_POPUP   13
