#define EDIT_WINDOW_ACT_X            3
#define EDIT_WINDOW_ACT_Y            5
#define EDIT_WINDOW_ACT_W            7
#define EDIT_WINDOW_ACT_H            9
#define EDIT_WINDOW_SNAPX            14
#define EDIT_WINDOW_SNAPY            17
#define EDIT_WINDOW_CLOSER           23
#define EDIT_WINDOW_INFO             24
#define EDIT_WINDOW_HSLIDE           27
#define EDIT_WINDOW_LFARROW          28
#define EDIT_WINDOW_RTARROW          29
#define EDIT_WINDOW_SIZER            30
#define EDIT_WINDOW_DNARROW          31
#define EDIT_WINDOW_VSLIDE           33
#define EDIT_WINDOW_UPARROW          34
#define EDIT_WINDOW_FULLER           35
#define EDIT_WINDOW_ICONIFIER        36
#define EDIT_WINDOW_BACKDROP         37
#define EDIT_WINDOW_NAME             38
#define EDIT_WINDOW_MOVER            39
#define EDIT_WINDOW_HOTCLOSEBOX      40
#define EDIT_WINDOW_OBLIST           42
#define EDIT_WINDOW_STAY             44
#define EDIT_WINDOW_ICON             46
#define EDIT_WINDOW_GHOSTICON        48
#define EDIT_WINDOW_ICONACCEPT       50
#define EDIT_WINDOW_TOOLBOX          52
#define EDIT_WINDOW_NAMESTR          58
#define EDIT_WINDOW_INFOSTR          59
#define EDIT_WINDOW_HELP_TITLE       66
#define EDIT_WINDOW_HELP_FILE        67
#define EDIT_WINDOW_MENU             74
#define EDIT_WINDOW_TOOLBAR          76
#define EDIT_WINDOW_WORK             78
#define EDIT_WINDOW_ICONBLK          80
#define EDIT_WINDOW_USER             82
#define EDIT_WINDOW_OPEN             97
#define EDIT_WINDOW_CREATE           99
#define EDIT_WINDOW_SERVICE         101
#define EDIT_WINDOW_INIT            103
#define EDIT_WINDOW_KEYS            105
#define EDIT_WINDOW_CHANGE          107
#define EDIT_WINDOW_REDRAW          109
#define EDIT_WINDOW_TOPPED          111
#define EDIT_WINDOW_CLOSED          113
#define EDIT_WINDOW_FULLED          115
#define EDIT_WINDOW_ARROWED         117
#define EDIT_WINDOW_HSLIDEFUNC      119
#define EDIT_WINDOW_VSLIDEFUNC      121
#define EDIT_WINDOW_MOVED           123
#define EDIT_WINDOW_SIZED           125
#define EDIT_WINDOW_ICONIFY         127
#define EDIT_WINDOW_UNICONIFY       129
#define EDIT_WINDOW_GEMSCRIPT       131
