#define MEN_LIST_NEW    16
#define MEN_LIST_FREE   18
#define MEN_LIST_OPEN   22
#define MEN_LIST_NAME   24
#define MEN_LIST_SCOPE  26

#define DIFF_TYPE_OLDTYPE 3
#define DIFF_TYPE_NEWTYPE 4
#define DIFF_TYPE_NEW     6
#define DIFF_TYPE_OLD     8
#define DIFF_TYPE_CANCEL 10
#define DIFF_TYPE_TITLE  12

#define INFO_LIST_FILENAME  8
#define INFO_LIST_LISTNAME  9
#define INFO_LIST_OBJNAME  10
#define INFO_LIST_USED     11
#define INFO_LIST_USAGE    13

#define INFO_LISTSELF_USED     5
#define INFO_LISTSELF_OBJNAME  6
#define INFO_LISTSELF_FILENAME 7

#define INFO_SCOPE_LOCAL    2
#define INFO_SCOPE_GLOBAL   4
#define INFO_SCOPE_OK       6
#define INFO_SCOPE_CANCEL   8

